In [80]:
# Necessary imports
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import patsy
import seaborn as sns
from seaborn import plt
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import RidgeCV
%matplotlib inline


In [82]:
df = pd.read_csv('customers_stats_full.csv', sep="|", engine='python',verbose=True)
df_og = pd.read_csv('customers_stats_full.csv', sep="|", engine='python',verbose=True)

df.head()

Filled 3718 NA values in column SFDC_Trial_Start_Date__c
Filled 2247 NA values in column Google_Apps_Plan_ID__c
Filled 2170 NA values in column Google_Apps__c
Filled 3892 NA values in column GAPPS_Churn_Date__c
Filled 1260 NA values in column Industry
Filled 4017 NA values in column SFDC_Churn_Date__c
Filled 1622 NA values in column Territory__c
Filled 3072 NA values in column Assigned_CSM__c
Filled 3921 NA values in column SFDC_Trial_End_Date__c
Filled 2353 NA values in column Type
Filled 606 NA values in column BillingCountry
Filled 3417 NA values in column Region__c
Filled 142 NA values in column domain.auto_add_new_accounts
Filled 1459 NA values in column subscription.is_monthly
Filled 3715 NA values in column SFDC_Plan_Id__c
Filled 2734 NA values in column GAPPS_Paid_Start_Date__c
Filled 262 NA values in column Website
Filled 3899 NA values in column Churn_Notes__c
Filled 1456 NA values in column subscription.canceled
Filled 2660 NA values in column Google_Apps_Trial_Start_Date__c

Account_Tier__c  AnnualRevenue     Assigned_CSM__c  BASS_Subscription_Id__c  \
0               3            NaN  00560000002HJZLAA4                   170529   
1               3            NaN  00560000002IVvlAAG                      NaN   
2               3            NaN  005600000047ugcAAA                   170523   
3               3            NaN  005600000047ugcAAA                      NaN   
4               2            NaN  00560000002IVvlAAG                      NaN   

   Backupify_Logins__c  BillingCountry Churn_Notes__c  Cloud_Forward_Scale__c  \
0                  NaN   United States            NaN                     NaN   
1                  NaN   United States            NaN                     NaN   
2                  NaN        Colombia            NaN                     NaN   
3                  NaN  United Kingdom            NaN                     NaN   
4                  NaN   United States            NaN                     NaN   

  Company_Size_by_Number_of_Employees__c Contract_Renewal_Date__c  \
0                              101 - 250               2014-01-01   
1                              101 - 250               2014-01-01   
2                                    NaN                      NaN   
3                                26 - 50               2014-01-01   
4                              251 - 500               2014-01-01   

                ...               subscription.invoiced  \
0               ...                                 NaN   
1               ...                                True   
2               ...                                 NaN   
3               ...                                True   
4               ...                                True   

  domain.authentication_type domain.total_accounts  \
0                          4                    10   
1                          4                   256   
2                          4                  1184   
3                          4                   123   
4                          4                  1029   

  domain.send_owner_summary_email  domain.auto_add_new_accounts  \
0                            true                         false   
1                            true                         false   
2                            true                         false   
3                            true                         false   
4                            true                         false   

  domain.sites_for_owners_only  domain.unprotected_accounts_count  \
0                         true                                  8   
1                         true                                 60   
2                         true                               1169   
3                         true                                 54   
4                         true                                425   

  domain.notifications_count domain.s3_region_id  \
0                          2                 NaN   
1                          0                 NaN   
2                          0                 NaN   
3                          0                   1   
4                         66                 NaN   

  domain.child_app_access_enabled  
0                            true  
1                           false  
2                            true  
3                            true  
4                           false  

[5 rows x 228 columns]

In [83]:
cols = df.columns.map(lambda x:  x )
print cols

['Account_Tier__c' 'AnnualRevenue' 'Assigned_CSM__c'
 'BASS_Subscription_Id__c' 'Backupify_Logins__c' 'BillingCountry'
 'Churn_Notes__c' 'Cloud_Forward_Scale__c'
 'Company_Size_by_Number_of_Employees__c' 'Contract_Renewal_Date__c'
 'CreatedById' 'CreatedDate' 'Current_Plan_Type__c' 'Customer_Status__c'
 'Customer_Success_Relationship__c' 'Datto_Products__c' 'Domain_Users__c'
 'Domain__c' 'Feature_Requests__c' 'GAPPS_At_Risk__c' 'GAPPS_Churn_Date__c'
 'GAPPS_Churn_Reason__c' 'GAPPS_Churn__c'
 'GAPPS_Number_of_Users_Being_Backed_Up__c' 'GAPPS_Paid_Start_Date__c'
 'GAPPS_Paid__c' 'GAPPS_Reseller_ID__c' 'GAPPS_Total_Storage__c'
 'Google_Apps_Plan_ID__c' 'Google_Apps_Trial_End_Date__c'
 'Google_Apps_Trial_Start_Date__c' 'Google_Apps__c' 'Health_Score__c' 'Id'
 'Industry' 'LastActivityDate' 'LeanData__LD_EmailDomains__c'
 'LeanData__Search__c' 'Name' 'New_Subscription__c'
 'Number_of_Salesforce_Users__c' 'Other_SaaS_Applications_Being_USed__c'
 'Overall_Health__c' 'Potential_GB_Upsell__c' 'P

In [84]:
df["Churn_Notes__c"]


0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
       ... 
3996    NaN
3997    NaN
3998    NaN
3999    NaN
4000    NaN
4001    NaN
4002    NaN
4003    NaN
4004    NaN
4005    NaN
4006    NaN
4007    NaN
4008    NaN
4009    NaN
4010    NaN
4011    NaN
4012    NaN
4013    NaN
4014    NaN
4015    NaN
4016    NaN
4017    NaN
4018    NaN
4019    NaN
4020    NaN
4021    NaN
4022    NaN
4023    NaN
4024    NaN
4025    NaN
Name: Churn_Notes__c, dtype: object

In [85]:
churn_fields = ["Churn_Notes__c",'GAPPS_Churn_Date__c', 'GAPPS_Churn_Reason__c',
       'GAPPS_Churn__c','SFDC_Churn_Date__c', 'SFDC_Churn__c']

In [86]:
churn = df[churn_fields]
churn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4026 entries, 0 to 4025
Data columns (total 6 columns):
Churn_Notes__c           127 non-null object
GAPPS_Churn_Date__c      134 non-null object
GAPPS_Churn_Reason__c    131 non-null object
GAPPS_Churn__c           4026 non-null bool
SFDC_Churn_Date__c       9 non-null object
SFDC_Churn__c            4026 non-null bool
dtypes: bool(2), object(4)
memory usage: 165.1+ KB


In [87]:
def determine_churn(row):
    if np.nan_to_num(row["Churn_Notes__c"]) != 0:
        return 1
    elif np.nan_to_num(row["GAPPS_Churn_Date__c"]) != 0:
        return 1
    elif np.nan_to_num(row["GAPPS_Churn_Reason__c"]) != 0:
        return 1
    elif np.nan_to_num(row["GAPPS_Churn__c"]) == True:
        return 1
    elif np.nan_to_num(row["SFDC_Churn__c"]) == True:
        return 1    
    else:
        return 0
    
    
df["churned"] = 0

for index, row in churn.iterrows():
    df["churned"][index] = determine_churn(row)

df["churned"]

/Users/keith/miniconda/lib/python2.7/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
3996    0
3997    0
3998    0
3999    0
4000    0
4001    0
4002    0
4003    0
4004    0
4005    0
4006    0
4007    0
4008    0
4009    0
4010    0
4011    0
4012    0
4013    0
4014    0
4015    0
4016    0
4017    0
4018    0
4019    0
4020    0
4021    0
4022    0
4023    0
4024    0
4025    0
Name: churned, dtype: int64

In [88]:
df.corr()

AnnualRevenue  \
AnnualRevenue                                  1.000000   
BASS_Subscription_Id__c                        0.052691   
Backupify_Logins__c                           -0.102320   
Cloud_Forward_Scale__c                              NaN   
Customer_Success_Relationship__c              -0.113461   
Domain_Users__c                                0.226236   
GAPPS_At_Risk__c                                    NaN   
GAPPS_Churn__c                                 0.328970   
GAPPS_Number_of_Users_Being_Backed_Up__c      -0.064959   
GAPPS_Paid__c                                  0.054059   
GAPPS_Reseller_ID__c                           0.329564   
GAPPS_Total_Storage__c                        -0.034237   
Health_Score__c                               -0.059080   
New_Subscription__c                                 NaN   
Number_of_Salesforce_Users__c                  0.270532   
Overall_Health__c                             -0.099415   
Potential_GB_Upsell__c                        -0.003528   
Potential_Upsell__c                            0.318261   
Risk_Activity__c                               0.315994   
Risk_Relationship__c                          -0.063996   
Roll_Up_MRR__c                                 0.001550   
Roll_Up_Storage_Purchased__c                  -0.047595   
SFDC_At_Risk__c                                     NaN   
SFDC_Churn__c                                       NaN   
SFDC_Paid__c                                   0.114871   
Total_Opps__c                                  0.082970   
Total_Won_Opportunities__c                     0.001550   
type.question                                 -0.055633   
type.incident                                  0.005496   
type.task                                           NaN   
...                                                 ...   
issue_category.stalled_snapshot                     NaN   
issue_category.admin_cdr                            NaN   
pending.redmine                               -0.045152   
pending.follow_up                              0.040285   
pending.                                            NaN   
pending.user_response                         -0.055742   
pending.user_config                                 NaN   
pending.export                                      NaN   
pending.backup_job                                  NaN   
awaiting.                                           NaN   
awaiting.success                              -0.025608   
awaiting.sales                                      NaN   
awaiting.monitor                                    NaN   
awaiting.accounting                                 NaN   
awaiting.restore_pending                       0.082106   
awaiting.export_pending                             NaN   
awaiting.google                                     NaN   
awaiting.backup_pending                             NaN   
awaiting.user_removal_pending                       NaN   
comment_count                                 -0.045450   
Trial?                                              NaN   
Proactive                                      0.019249   
Unnamed: 214                                  -0.053925   
comments_per_ticket                           -0.043107   
domain.authentication_type                     0.008488   
domain.total_accounts                         -0.063557   
domain.unprotected_accounts_count             -0.051542   
domain.notifications_count                    -0.019143   
domain.s3_region_id                                 NaN   
churned                                        0.297151   

                                          BASS_Subscription_Id__c  \
AnnualRevenue                                            0.052691   
BASS_Subscription_Id__c                                  1.000000   
Backupify_Logins__c                                     -0.176874   
Cloud_Forward_Scale__c                                  -0.212485   
Customer_Success_Relationship__c      

In [89]:
# sns.pairplot(df, size = 1.2, aspect=1.5)

In [90]:
cols = df.columns - churn_fields - ["churned"]
print cols

Index([u'Account_Tier__c', u'AnnualRevenue', u'Assigned_CSM__c',
       u'BASS_Subscription_Id__c', u'Backupify_Logins__c', u'BillingCountry',
       u'Cloud_Forward_Scale__c', u'Company_Size_by_Number_of_Employees__c',
       u'Contract_Renewal_Date__c', u'CreatedById',
       ...
       u'tags.success', u'tags.trial_alerted', u'tags.trial_yes',
       u'tags.user_config', u'tags.user_removal_pending',
       u'tags.user_response', u'type.incident', u'type.problem',
       u'type.question', u'type.task'],
      dtype='object', length=222)


/Users/keith/miniconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: using '-' to provide set differences with Indexes is deprecated, use .difference()
  if __name__ == '__main__':


In [91]:
expression = "churned ~ "
terms = cols.map(lambda x: x + " + ")

print terms

['Account_Tier__c + ' 'AnnualRevenue + ' 'Assigned_CSM__c + '
 'BASS_Subscription_Id__c + ' 'Backupify_Logins__c + ' 'BillingCountry + '
 'Cloud_Forward_Scale__c + ' 'Company_Size_by_Number_of_Employees__c + '
 'Contract_Renewal_Date__c + ' 'CreatedById + ' 'CreatedDate + '
 'Current_Plan_Type__c + ' 'Customer_Status__c + '
 'Customer_Success_Relationship__c + ' 'Datto_Products__c + '
 'Domain_Users__c + ' 'Domain__c + ' 'Feature_Requests__c + '
 'GAPPS_At_Risk__c + ' 'GAPPS_Number_of_Users_Being_Backed_Up__c + '
 'GAPPS_Paid_Start_Date__c + ' 'GAPPS_Paid__c + ' 'GAPPS_Reseller_ID__c + '
 'GAPPS_Total_Storage__c + ' 'Google_Apps_Plan_ID__c + '
 'Google_Apps_Trial_End_Date__c + ' 'Google_Apps_Trial_Start_Date__c + '
 'Google_Apps__c + ' 'Health_Score__c + ' 'Id + ' 'Industry + '
 'LastActivityDate + ' 'LeanData__LD_EmailDomains__c + '
 'LeanData__Search__c + ' 'Name + ' 'New_Subscription__c + '
 'Number_of_Salesforce_Users__c + '
 'Other_SaaS_Applications_Being_USed__c + ' 'Overall_Heal

In [92]:
algo = expression + ' '.join(str(x) for x in terms) 
print algo

churned ~ Account_Tier__c +  AnnualRevenue +  Assigned_CSM__c +  BASS_Subscription_Id__c +  Backupify_Logins__c +  BillingCountry +  Cloud_Forward_Scale__c +  Company_Size_by_Number_of_Employees__c +  Contract_Renewal_Date__c +  CreatedById +  CreatedDate +  Current_Plan_Type__c +  Customer_Status__c +  Customer_Success_Relationship__c +  Datto_Products__c +  Domain_Users__c +  Domain__c +  Feature_Requests__c +  GAPPS_At_Risk__c +  GAPPS_Number_of_Users_Being_Backed_Up__c +  GAPPS_Paid_Start_Date__c +  GAPPS_Paid__c +  GAPPS_Reseller_ID__c +  GAPPS_Total_Storage__c +  Google_Apps_Plan_ID__c +  Google_Apps_Trial_End_Date__c +  Google_Apps_Trial_Start_Date__c +  Google_Apps__c +  Health_Score__c +  Id +  Industry +  LastActivityDate +  LeanData__LD_EmailDomains__c +  LeanData__Search__c +  Name +  New_Subscription__c +  Number_of_Salesforce_Users__c +  Other_SaaS_Applications_Being_USed__c +  Overall_Health__c +  Potential_GB_Upsell__c +  Potential_Upsell__c +  Proactive +  Region__c + 

In [93]:
# lm = smf.ols(algo, data=df)
# # Fit the model
# fit = lm.fit()
# # Check out the results
# fit.summary()

In [94]:
df[cols]

Account_Tier__c  AnnualRevenue     Assigned_CSM__c  \
0                  3            NaN  00560000002HJZLAA4   
1                  3            NaN  00560000002IVvlAAG   
2                  3            NaN  005600000047ugcAAA   
3                  3            NaN  005600000047ugcAAA   
4                  2            NaN  00560000002IVvlAAG   
5                NaN            NaN                 NaN   
6                  2            NaN  00560000002IVvlAAG   
7                  3            NaN  00560000002IVvlAAG   
8                  2            NaN  00560000002IVvlAAG   
9                  2            NaN  005600000047ugcAAA   
10                 3            NaN  005600000047ugcAAA   
11               NaN            NaN                 NaN   
12                 3            NaN  005600000047ugcAAA   
13                 3          32000  00560000002HJZLAA4   
14               NaN            NaN                 NaN   
15                 3            NaN  00560000002HJZLAA4   
16                 2            NaN  005600000047ugcAAA   
17                 2            NaN  00560000002IVvlAAG   
18                 3            NaN  00560000002IVvlAAG   
19               NaN            NaN                 NaN   
20               NaN            NaN                 NaN   
21                 2            NaN  005600000047ugcAAA   
22                 3            NaN  00560000002IVvlAAG   
23                 3            NaN  00560000002IVvlAAG   
24                 3            NaN  00560000002HJZLAA4   
25                 3            NaN  00560000002IVvlAAG   
26                 3            NaN  00560000002HJZLAA4   
27                 2            NaN  00560000002IVvlAAG   
28                 3       20200000  00560000002HJZLAA4   
29                 3            NaN  005600000047ugcAAA   
...              ...            ...                 ...   
3996             NaN            NaN                 NaN   
3997             NaN            NaN                 NaN   
3998             NaN            NaN                 NaN   
3999               3            NaN  00560000002HJZLAA4   
4000             NaN            NaN                 NaN   
4001             NaN            NaN                 NaN   
4002             NaN            NaN                 NaN   
4003             NaN            NaN                 NaN   
4004               3            NaN  00560000002IVvlAAG   
4005             NaN            NaN                 NaN   
4006             NaN            NaN                 NaN   
4007             NaN            NaN                 NaN   
4008             NaN            NaN                 NaN   
4009             NaN            NaN                 NaN   
4010             NaN            NaN                 NaN   
4011        Standard            NaN                 NaN   
4012             NaN            NaN                 NaN   
4013             NaN            NaN                 NaN   
4014             NaN            NaN                 NaN   
4015             NaN            NaN                 NaN   
4016               3            NaN  00560000002HJZLAA4   
4017             NaN            NaN                 NaN   
4018             NaN            NaN                 NaN   
4019             NaN            NaN                 NaN   
4020               3            NaN  005600000047ugcAAA   
4021               1            NaN  005600000047ugcAAA   
4022             NaN            NaN                 NaN   
4023             NaN            NaN                 NaN   
4024             NaN            NaN                 NaN   
4025               2            NaN  005600000047ugcAAA   

      BASS_Subscription_Id__c  Backupify_Logins__c  BillingCountry  \
0                      170529                  NaN   United States   
1                         NaN                  NaN   United States   
2                      170523                  NaN        Colombia   
3                         NaN                  NaN  United Kingdom

In [95]:
df["Cloud_Forward_Scale__c"] = df["Cloud_Forward_Scale__c"].map(lambda x: 0 if np.nan_to_num(x) == 0 else x )

In [96]:
df["Account_Tier__c"] = df["Account_Tier__c"].map(lambda x: 0 if np.nan_to_num(x) == 0 else x )

In [97]:
df["Backupify_Logins__c"] = df["Backupify_Logins__c"].map(lambda x: 0 if np.nan_to_num(x) == 0 else x )

In [98]:
df["Number_of_Salesforce_Users__c"]= df["Number_of_Salesforce_Users__c"].map(lambda x: 0 if np.nan_to_num(x) == 0 else x )

In [99]:
df["Datto_Products__c"] = df["Datto_Products__c"].map(lambda x: 0 if np.nan_to_num(x) == 0 else x )

In [100]:
df["Zuora_Account_Link__c"] = df["Zuora_Account_Link__c"].map(lambda x: 0 if x == "Did not pay via Zuora" else 1)

In [101]:
df["domain.child_app_access_enabled"]  = df["domain.child_app_access_enabled"].map(lambda x: 1 if x == "true" else 0)

In [102]:
df["domain.sites_for_owners_only"]  = df["domain.sites_for_owners_only"].map(lambda x: 1 if x == "true" else 0)  


In [103]:
df["domain.send_owner_summary_email"] = df["domain.send_owner_summary_email"].map(lambda x: 1 if x == "true" else 0) 

In [104]:
df["Feature_Requests__c"] = df["Feature_Requests__c"].map(lambda x: 0 if np.nan_to_num(x) == 0 else 1 )

In [105]:
dummies_df = pd.get_dummies(df["Company_Size_by_Number_of_Employees__c"])

df[dummies_df.columns] = dummies_df

df.head()

Account_Tier__c  AnnualRevenue     Assigned_CSM__c  BASS_Subscription_Id__c  \
0               3            NaN  00560000002HJZLAA4                   170529   
1               3            NaN  00560000002IVvlAAG                      NaN   
2               3            NaN  005600000047ugcAAA                   170523   
3               3            NaN  005600000047ugcAAA                      NaN   
4               2            NaN  00560000002IVvlAAG                      NaN   

   Backupify_Logins__c  BillingCountry Churn_Notes__c  Cloud_Forward_Scale__c  \
0                    0   United States            NaN                       0   
1                    0   United States            NaN                       0   
2                    0        Colombia            NaN                       0   
3                    0  United Kingdom            NaN                       0   
4                    0   United States            NaN                       0   

  Company_Size_by_Number_of_Employees__c Contract_Renewal_Date__c   ...    \
0                              101 - 250               2014-01-01   ...     
1                              101 - 250               2014-01-01   ...     
2                                    NaN                      NaN   ...     
3                                26 - 50               2014-01-01   ...     
4                              251 - 500               2014-01-01   ...     

  25 and Under 2501 - 5000 251 - 500 26 - 50  5001 - 10000 501 - 1000  \
0            0           0         0       0             0          0   
1            0           0         0       0             0          0   
2            0           0         0       0             0          0   
3            0           0         0       1             0          0   
4            0           0         1       0             0          0   

   51 - 100 Under 25  Under 50 Unknown  
0         0        0         0       0  
1         0        0         0       0  
2         0        0         0       0  
3         0        0         0       0  
4         0        0         0       0  

[5 rows x 243 columns]

In [106]:
def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in xrange(0, len(l), n):
        yield l[i:i+n]

chs = list(chunks(cols, 10))
for chunk in chs:
    print df[chunk].head()


  Account_Tier__c  AnnualRevenue     Assigned_CSM__c  BASS_Subscription_Id__c  \
0               3            NaN  00560000002HJZLAA4                   170529   
1               3            NaN  00560000002IVvlAAG                      NaN   
2               3            NaN  005600000047ugcAAA                   170523   
3               3            NaN  005600000047ugcAAA                      NaN   
4               2            NaN  00560000002IVvlAAG                      NaN   

   Backupify_Logins__c  BillingCountry  Cloud_Forward_Scale__c  \
0                    0   United States                       0   
1                    0   United States                       0   
2                    0        Colombia                       0   
3                    0  United Kingdom                       0   
4                    0   United States                       0   

  Company_Size_by_Number_of_Employees__c Contract_Renewal_Date__c  \
0                              101 - 250       

In [107]:
fields_to_drop = ["Contract_Renewal_Date__c","Customer_Status__c",
                  "GAPPS_Paid_Start_Date__c", "Google_Apps_Trial_End_Date__c",
                  "Google_Apps_Trial_Start_Date__c" ]

In [108]:
df["Datto_Products__c"]

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
3996    0
3997    0
3998    0
3999    0
4000    0
4001    0
4002    0
4003    0
4004    0
4005    0
4006    0
4007    0
4008    0
4009    0
4010    0
4011    0
4012    0
4013    0
4014    0
4015    0
4016    0
4017    0
4018    0
4019    0
4020    0
4021    0
4022    0
4023    0
4024    0
4025    0
Name: Datto_Products__c, dtype: object

In [109]:
df = df.fillna(0)

In [110]:
dummies_df = pd.get_dummies(df["Google_Apps_Plan_ID__c"])
df[dummies_df.columns] = dummies_df


In [111]:
df["SFDC_Trial_Start_Date__c"] = pd.to_datetime(df["SFDC_Trial_Start_Date__c"])

In [112]:
df.head()

Account_Tier__c  AnnualRevenue     Assigned_CSM__c  BASS_Subscription_Id__c  \
0               3              0  00560000002HJZLAA4                   170529   
1               3              0  00560000002IVvlAAG                        0   
2               3              0  005600000047ugcAAA                   170523   
3               3              0  005600000047ugcAAA                        0   
4               2              0  00560000002IVvlAAG                        0   

   Backupify_Logins__c  BillingCountry Churn_Notes__c  Cloud_Forward_Scale__c  \
0                    0   United States              0                       0   
1                    0   United States              0                       0   
2                    0        Colombia              0                       0   
3                    0  United Kingdom              0                       0   
4                    0   United States              0                       0   

  Company_Size_by_Number_of_Employees__c Contract_Renewal_Date__c  \
0                              101 - 250               2014-01-01   
1                              101 - 250               2014-01-01   
2                                      0                        0   
3                                26 - 50               2014-01-01   
4                              251 - 500               2014-01-01   

      ...      501 - 1000 51 - 100 Under 25 Under 50  Unknown  0  Enterprise  \
0     ...               0        0        0        0        0  0           0   
1     ...               0        0        0        0        0  1           0   
2     ...               0        0        0        0        0  0           0   
3     ...               0        0        0        0        0  1           0   
4     ...               0        0        0        0        0  1           0   

  Enterprise Plus  Pro 500 Professional  
0               0        0            1  
1               0        0            0  
2               0        0            1  
3               0        0            0  
4               0        0            0  

[5 rows x 248 columns]

In [113]:
cols = df.columns


In [114]:
date_fields =     [u'Contract_Renewal_Date__c',
        u'CreatedDate',
        u'GAPPS_Churn_Date__c',
        u'GAPPS_Paid_Start_Date__c',
        u'Google_Apps_Trial_End_Date__c',
        u'Google_Apps_Trial_Start_Date__c',
        u'LastActivityDate',
        u'SFDC_Churn_Date__c',
        u'SFDC_Paid_Start_Date__c',
        u'SFDC_Trial_End_Date__c',
        u'SFDC_Trial_Start_Date__c']

# convert datetimes to from from now
# for dfield in date_fields:
#     df[dfield] = pd.to_datetime(df[dfield])

# drop fields

df.drop(df[date_fields], axis=1, inplace=True)


In [115]:
df["domain.auto_add_new_accounts"] = df["domain.auto_add_new_accounts"].map(lambda x: 1 if x == True else 0)


In [116]:
dummies_df = pd.get_dummies(df["Industry"])

df[dummies_df.columns] = dummies_df



In [117]:
dummies_df = pd.get_dummies(df["Territory__c"])

df[dummies_df.columns] = dummies_df


In [118]:
dummies_df = pd.get_dummies(df["Territory__c"])

df[dummies_df.columns] = dummies_df

In [119]:

dummies_df = pd.get_dummies(df["BillingCountry"])

df[dummies_df.columns] = dummies_df

In [120]:

dummies_df = pd.get_dummies(df["Type"])

df[dummies_df.columns] = dummies_df


In [121]:


dummies_df = pd.get_dummies(df["Company_Size_by_Number_of_Employees__c"])

df[dummies_df.columns] = dummies_df

In [122]:

dummies_df = pd.get_dummies(df["Success_Strategy__c"])

df[dummies_df.columns] = dummies_df

In [123]:


dummies_df = pd.get_dummies(df["Salesforce_edition__c"])

df[dummies_df.columns] = dummies_df

In [124]:

dummies_df = pd.get_dummies(df["Current_Plan_Type__c"])

df[dummies_df.columns] = dummies_df

In [125]:

dummies_df = pd.get_dummies(df["SFDC_Plan_Id__c"])

df[dummies_df.columns] = dummies_df

In [126]:


dummies_df = pd.get_dummies(df["Customer_Status__c"])

df[dummies_df.columns] = dummies_df

In [127]:


dummies_df = pd.get_dummies(df["Region__c"])

df[dummies_df.columns] = dummies_df

In [128]:


dummies_df = pd.get_dummies(df["Datto_Products__c"])

df[dummies_df.columns] = dummies_df

In [129]:
def count_saas_apps(x):
    if isinstance(x, ( int, long )): 
        return 0
    else:
        return len(x.split(";"))
    
df["Other_SaaS_Applications_Being_USed__c"] = df["Other_SaaS_Applications_Being_USed__c"].map(count_saas_apps  )

In [130]:
my_cols = set(df.columns)


fields_to_remove = ['churned',
'Assigned_CSM__c',
'CreatedById',
'Id',
"tags.acct_pro100",
"Google_Apps__c",
"Google_Apps_Plan_ID__c",
"Industry",
"Territory__c",
"Type",
"BillingCountry",
"Company_Size_by_Number_of_Employees__c",
"LeanData__Search__c",
"LeanData__LD_EmailDomains__c",
"Success_Strategy__c",
"Salesforce_edition__c",
"Website",
"Current_Plan_Type__c",
"Domain__c",
"Name",
"SFDC_Plan_Id__c",
"Region__c",
"Customer_Status__c",
"Datto_Products__c",
"Account_Tier__c"] + churn_fields


for field in fields_to_remove:
    if field in my_cols:
        my_cols.remove(field)


my_cols = list(my_cols)
df2 = df[my_cols]
X_train, X_test, y_train, y_test = train_test_split(df2, df["churned"], test_size=0.3)
X_train.columns

Index([                                          0,
                         u'tags.prod_social_media',
                                  u'AnnualRevenue',
                                u'tags.acct_other',
                        u'awaiting.backup_pending',
               u'Customer_Success_Relationship__c',
                                       u'tags.n/a',
                                    u'tags.export',
         u'issue_category.admin_re_enable_service',
                                 u'tags.follow_up',
       ...
                                    u'Interest In',
               u'Industrial Machinery & Equipment',
                                       u'tags.hot',
                          u'tags.standard_partner',
       u'Computer Networking Equipment; Telecommu',
                                       u'Prospect',
                                        u'Pro 500',
                                   u'tags.restore',
                                      u'Singapore',
 

In [131]:
# df["Total_Opps__c"]

In [132]:
lr = LinearRegression()
cols = X_train.columns
chs = list(chunks(cols, 1))
# for chunk in chs:
#     print X_train[chunk].head(2)
#     lr.fit(X_train[chunk], y_train)
#     print lr.score(X_test[chunk], y_test)


In [133]:
churned_corr_raw = df.corr()["churned"]
# for val in churned_corr:
#     print val
churned_corr = churned_corr_raw.copy(deep=True)
churned_corr.sort_values(inplace=True)
churned_corr = churned_corr.dropna()
churned_corr

domain.authentication_type             -0.098070
domain.sites_for_owners_only           -0.068077
25 and Under                           -0.046097
domain.send_owner_summary_email        -0.045200
Risk_Activity__c                       -0.045168
Risk_Relationship__c                   -0.044934
Health_Score__c                        -0.044279
Prospect                               -0.042081
domain.child_app_access_enabled        -0.032591
Customer                               -0.032350
Customer_Success_Relationship__c       -0.030265
Consulting                             -0.029628
issue_category.inquiry                 -0.028377
tags.inquiry                           -0.028377
priority.high                          -0.027141
Finance                                -0.025982
Zuora_Account_Link__c                  -0.025857
tags.user_response                     -0.022503
pending.user_response                  -0.022503
E-Commerce                             -0.022408
domain.total_account

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4026 entries, 0 to 4025
Columns: 456 entries, Account_Tier__c to Interest In;Veeam
dtypes: bool(7), float64(259), int64(162), object(28)
memory usage: 13.8+ MB


In [135]:
lr.fit(X_train, y_train)
lr.score(X_test,y_test)    

0.60856103551351404

In [153]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=20)
clf = clf.fit(X_train, y_train)


In [154]:
clf.score(df2, df['churned'])

0.99354197714853454

## 

In [155]:
for index, row in df2.iterrows():
    predict = clf.predict(row)
    if df['churned'][index] != predict:
        if predict == 1:
            print predict
            print index

In [156]:
print df_og.iloc[193]['Id']
print df_og.iloc[2090]['Id']
print df_og.iloc[2096]['Id']


0016000000q3UyXAAU
0016000000q2bQ9AAI
0016000000q3UyXAAU


In [157]:
cols = df.columns
print cols

Index([                       u'Account_Tier__c',
                                u'AnnualRevenue',
                              u'Assigned_CSM__c',
                      u'BASS_Subscription_Id__c',
                          u'Backupify_Logins__c',
                               u'BillingCountry',
                               u'Churn_Notes__c',
                       u'Cloud_Forward_Scale__c',
       u'Company_Size_by_Number_of_Employees__c',
                                  u'CreatedById',
       ...
                                 u'Was Customer',
                                         u'APAC',
                                            u'E',
                                       u'Europe',
                                        u'LATAM',
                         u'Middle East / Africa',
                                u'North America',
                             u'Current Customer',
                                  u'Interest In',
                            u'Interest 

In [158]:
for index, row in df2.iterrows():
    predict = clf.predict_proba(row)
#     if df['churned'][index] != predict:
#         if predict == 1:
    print predict
#             print index


[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.75  0.25]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 0.95  0.05]]
[[ 1.  0.]]
[[ 0.95  0.05]]
[[ 0.95  0.05]]
[[ 1.  0.]]
